### ISSUE TITLE
Zulip topic is only renamed for messages after MCP issue rename occurs

### ISSUE THREAD

**Issue by camelid** [rust-lang/triagebot#1228]
It happened [here](https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Lang.20Item.20for.20Transmutability.20compiler-team.23411/near/228833214). triagebot renamed the topic of the "renaming this Zulip topic" message, which effectively splits the topic in two, when it should have renamed the topic of the original "new proposal" message.

The code that is responsible for renaming the topic is here:

https://github.com/rust-lang/triagebot/blob/3272855862cf4bb2d3c1a729e335e77dd124ce42/src/handlers/major_change.rs#L138-L143

Another bug is that renaming the Zulip topic breaks [the link in the MCP issue](https://github.com/rust-lang/compiler-team/issues/411#issuecomment-790851188)—which is what #711 was originally trying to fix (see #701, the short summary is that someone manually renamed the Zulip topic, which broke the link in the MCP issue).

Fixing these issues is probably going to be difficult. I'm not sure what the right solution is.

**Comment by camelid** [comment]
See also #706, which was another way to approach #701.

**Comment by skippy10110** [comment]
I was recently bit by this and ended up with 3 topics for my MCP. Thankfully the discussion didn't fork and stayed on the originally named topic.

I think this can be fixed by just using the ```change_all``` [propagate_mode](https://zulip.com/api/update-message#parameter-propagate_mode) when editing the topic. See also [Add API endpoint for renaming topics](https://github.com/zulip/zulip/issues/15846).

I also just noticed that ```change_all``` was already discussed in #701, but based on this [comment](https://github.com/rust-lang/triagebot/issues/701#issuecomment-660399862) it looks like the update message API didn't exist at the time and was only added later in #711.

I'm going to post a PR as this is just a simple one line fix (in theory...), however I don't have any kind of triagebot dev instance running to test this out myself.

**Comment by skippy10110** [comment]
Oh, I've posted my PR, but now I think I may have misunderstood this bug. Is the issue not that the "Zulip topic is only renamed for messages after MCP issue rename occurs", but instead that doing so breaks the links in the MCP?

**Comment by camelid** [comment]
I think `change_all` didn't exist before.
