### ISSUE TITLE
Support `@rustbot move $repo`

### ISSUE THREAD

**Issue by Centril** [rust-lang/triagebot#166]
Does GitHub support this?
- https://developer.github.com/changes/2017-11-09-repository-transfer-api-preview/

https://discordapp.com/channels/442252698964721669/443148290352218115/624290071985782784

**Comment by kellda** [comment]
What is the use case of this command ?

**Comment by Nilstrieb** [comment]
This would be nice to have, people often open issues on rust-lang/rust that should be transferred to somewhere else. Even though I have perms for that repo, I don't have perms for, say, clippy, so I can't move anything to clippy.

I think it would be fine if this command was entirely unrestricted, but it should at least be so that all org members can do it.

**Comment by apiraino** [comment]
> people often open issues on rust-lang/rust that should be transferred to somewhere else

How often, more or less? (Asking because I am not usually on the first line for new issues).

IIUC the [GH documentation](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role), users granted the `Transfer issues` permission should have `Write`, `Maintain` and `Admin` permissions on the repository (unclear if on the source repo, destination repo or both).

Personally I find this a potential source of abuse and disruption. Maybe I'm just a bit pessimistic :slightly_smiling_face:

**Comment by Nilstrieb** [comment]
I don't have numbers. Not *that* often, but every once in a while, clippy being the most common.

> unclear if on the source repo, destination repo or both).

Both!

So this would already be useful if it was restricted to org members.

**Comment by Nilstrieb** [comment]
Yeah, transfering issues.

**Comment by fbstj** [comment]
bikeshed: maybe it should be `move-to` instead?

would rustbot then mark the comment as hidden/complete after the move?

**Comment by ehuss** [comment]
My bikeshed would be "transfer" to use the same lingo as GitHub.

(I still assert this issue seems to originally have been to move a repo.)
