### ISSUE TITLE
Reply with an error message if the wrong username is pinged

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/triagebot#985]
Triagebot uses @rustbot on GitHub and `@triagebot` on Zulip, and it could happen that someone pings `@triagebot` on GitHub by mistake. If triagebot detects a `@triagebot` ping on GitHub with a valid command, an error message should be posted to alert the user they pinged the wrong bot.

**Comment by camelid** [comment]
It seems to me that it might be tricky to only respond to `@triagebot` if there was a valid command – it seems to me that we should always respond to `@triagebot`, at least on repos that have it enabled.

**Comment by Mark-Simulacrum** [comment]
I think we should just accept either and not complain. In the future if it becomes a problem (e.g. the owner of the triagebot account reaches out) we can alter that behavior.

**Comment by camelid** [comment]
I was thinking of suggesting that, but I thought you might think that was a bad idea :)

I do feel concerned that anytime that user is pinged someone will get an error from rustbot :/. Personally I think complaining is the best option because it points people clearly to the right way of doing it. People don't use the wrong name too often, so it's not a big deal to have them try again.

But I think ideally we would only respond to `@triagebot` on repos that have rustbot enabled – that would avoid annoying the owner of `@triagebot` on GitHub.

**Comment by Mark-Simulacrum** [comment]
Ultimately triagebot doesn't listen outside the rust-lang org and the repos in there will tend to all enable it, so I don't think that's all that important.

I think just doing what people ask is better than forcing a retry (that might get missed in notifications etc). I don't really see it as important that people get it right for the time being.

**Comment by camelid** [comment]
> Ultimately triagebot doesn't listen outside the rust-lang org

Oh, I didn't realize that. I think accepting `@triagebot` is fine then.
